# backend/services/session_service.py

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from backend.core.security import hash_token
from backend.models.session import Session as UserSession
from backend.models.user import User
from backend.services.token_service import TokenService


class InvalidSessionError(Exception):
    """Raised when a session is missing, expired, or revoked."""


class SessionNotFoundError(Exception):
    """Raised when a session ID does not match any stored session."""


class RefreshTokenReuseError(Exception):
    """
    Raised when a previously-rotated refresh token is presented again.

    The entire token family is revoked when reuse is detected.
    """


class SessionService:
    """
    Authentication session lifecycle management.

    A session represents a device/login instance.

    Authoritative session state:
        - is_active  -> True while the session may be used
        - revoked_at -> NULL while the session may be used
        - expires_at -> future datetime while the session may be used

    Raw refresh tokens are never persisted; only their hash is stored.
    The stored hash is treated as immutable history data: sessions are
    invalidated through the revocation fields, never by NULLing the hash.
    """

    # ============================================================
    # REVOCATION REASONS
    # ============================================================

    REASON_LOGOUT = "logout"
    REASON_REFRESH_TOKEN_REUSE = "refresh_token_reuse"
    REASON_PASSWORD_RESET = "password_reset"
    REASON_ADMIN = "admin"

    # ============================================================
    # TIME
    # ============================================================

    @staticmethod
    def utc_now() -> datetime:
        return datetime.now(timezone.utc)

    # ============================================================
    # CREATE SESSION
    # ============================================================

    @staticmethod
    async def create_session(
        db: AsyncSession,
        user: User,
        device_id: str = "unknown",
    ) -> tuple[UserSession, dict]:
        """
        Create an authentication session and its token pair.

        The session ID is generated by the database/model layer.
        """

        # Use a temporary placeholder so the NOT NULL constraint is
        # satisfied on the first flush (we need the generated id to
        # build the real token pair).
        _TEMP_HASH = "pending"

        session = UserSession(
            user_id=user.id,
            device_id=device_id,
            is_active=True,
            refresh_token_hash=_TEMP_HASH,
            expires_at=TokenService.get_refresh_expiry(),
            last_used_at=SessionService.utc_now(),
        )

        db.add(session)
        await db.flush()

        token_data = TokenService.create_token_pair(
            user_id=user.id,
            session_id=session.id,
        )

        session.refresh_token_hash = (
            token_data["refresh_token_hash"]
        )

        session.expires_at = (
            token_data["refresh_expires_at"]
        )

        session.last_used_at = (
            SessionService.utc_now()
        )

        await db.flush()

        return session, token_data

    # ============================================================
    # GET SESSION
    # ============================================================

    @staticmethod
    async def get_by_id(
        db: AsyncSession,
        session_id: UUID,
    ) -> Optional[UserSession]:
        """
        Retrieve a session by ID.
        """

        return await db.scalar(
            select(UserSession).where(
                UserSession.id == session_id
            )
        )

    @staticmethod
    async def get_user_session(
        db: AsyncSession,
        user_id: UUID,
        session_id: UUID,
    ) -> Optional[UserSession]:
        """
        Retrieve a session belonging to a specific user.
        """

        return await db.scalar(
            select(UserSession).where(
                UserSession.id == session_id,
                UserSession.user_id == user_id,
            )
        )

    # ============================================================
    # SESSION VALIDATION
    # ============================================================

    @staticmethod
    def is_valid(
        session: UserSession,
    ) -> bool:
        """
        Determine whether a session is currently usable.
        """

        if not session.is_active:
            return False

        if session.revoked_at is not None:
            return False

        expires_at = session.expires_at

        if expires_at is None:
            return False

        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(
                tzinfo=timezone.utc
            )

        return expires_at > SessionService.utc_now()

    @staticmethod
    def ensure_valid(
        session: UserSession,
    ) -> None:
        """
        Raise an error when a session is invalid.
        """

        if not SessionService.is_valid(session):
            raise InvalidSessionError(
                "Authentication session is invalid or expired."
            )

    # ============================================================
    # REFRESH TOKEN VALIDATION
    # ============================================================

    @staticmethod
    async def validate_refresh_token(
        db: AsyncSession,
        session: UserSession,
        refresh_token: str,
    ) -> bool:
        """
        Validate session state and refresh-token hash.
        """

        if not SessionService.is_valid(session):
            return False

        if not session.refresh_token_hash:
            return False

        return TokenService.verify_refresh_token(
            refresh_token,
            session.refresh_token_hash,
        )

    # ============================================================
    # ROTATE SESSION TOKEN
    # ============================================================

    @staticmethod
    async def rotate_refresh_token(
        db: AsyncSession,
        session: UserSession,
        refresh_token: str,
    ) -> dict:
        """
        Rotate the refresh token and issue a new access token.

        The old refresh token becomes invalid immediately because
        its stored hash is replaced.

        Reuse detection:
        If a still-valid session is presented with a token that no
        longer matches the stored hash, the token is an old,
        already-rotated one. The whole token family is revoked and
        RefreshTokenReuseError is raised.
        """

        SessionService.ensure_valid(session)

        if await SessionService.validate_refresh_token(
            db,
            session,
            refresh_token,
        ):
            return await SessionService._rotate_session_token(
                db,
                session,
            )

        # Session is still valid but the presented token does not
        # match the current hash: reuse of an outdated token.
        await SessionService.revoke_token_family(
            db,
            session.token_family_id,
            reason=SessionService.REASON_REFRESH_TOKEN_REUSE,
        )

        raise RefreshTokenReuseError(
            "Refresh token reuse detected; token family revoked."
        )

    @staticmethod
    async def _rotate_session_token(
        db: AsyncSession,
        session: UserSession,
    ) -> dict:
        """
        Issue a new token generation for a validated session.
        """

        new_refresh_token = (
            TokenService.generate_refresh_token()
        )

        new_refresh_token_hash = (
            hash_token(new_refresh_token)
        )

        new_access_token = (
            TokenService.create_access_token(
                user_id=session.user_id,
                session_id=session.id,
            )
        )

        session.refresh_token_hash = (
            new_refresh_token_hash
        )

        session.expires_at = (
            TokenService.get_refresh_expiry()
        )

        session.last_used_at = (
            SessionService.utc_now()
        )

        await db.flush()

        return {
            "access_token": new_access_token,
            "refresh_token": new_refresh_token,
            "expires_in": (
                TokenService.get_access_expiry_seconds()
            ),
            "refresh_expires_in": (
                TokenService.get_refresh_expiry_seconds()
            ),
            "session_id": session.id,
        }

    # ============================================================
    # UPDATE LAST USED
    # ============================================================

    @staticmethod
    async def touch(
        db: AsyncSession,
        session: UserSession,
    ) -> UserSession:
        """
        Update session last-used timestamp.
        """

        session.last_used_at = (
            SessionService.utc_now()
        )

        await db.flush()

        return session

    # ============================================================
    # REVOKE ONE SESSION
    # ============================================================

    @staticmethod
    async def revoke_session(
        db: AsyncSession,
        session: UserSession,
        reason: str = REASON_LOGOUT,
    ) -> UserSession:
        """
        Revoke a single authentication session.

        The refresh-token hash is intentionally preserved for audit
        history; the session is invalidated through revoked_at and
        is_active.
        """

        now = SessionService.utc_now()

        session.revoked_at = now
        session.is_active = False
        session.revoke_reason = reason
        session.last_used_at = now

        await db.flush()

        return session

    # ============================================================
    # REVOKE BY ID
    # ============================================================

    @staticmethod
    async def revoke_by_id(
        db: AsyncSession,
        session_id: UUID,
        reason: str = REASON_LOGOUT,
    ) -> bool:
        """
        Revoke a session using its ID.
        """

        session = await SessionService.get_by_id(
            db,
            session_id,
        )

        if not session:
            return False

        # Already revoked: nothing to do.
        if session.revoked_at is not None or not session.is_active:
            return False

        await SessionService.revoke_session(
            db,
            session,
            reason=reason,
        )

        return True

    # ============================================================
    # REVOKE TOKEN FAMILY
    # ============================================================

    @staticmethod
    async def revoke_token_family(
        db: AsyncSession,
        token_family_id: UUID,
        reason: str = REASON_REFRESH_TOKEN_REUSE,
    ) -> int:
        """
        Revoke every active session that shares a token family.

        Used to invalidate an entire lineage of rotated tokens when
        reuse is detected.
        """

        result = await db.execute(
            update(UserSession)
            .where(
                UserSession.token_family_id == token_family_id,
                UserSession.is_active.is_(True),
            )
            .values(
                revoked_at=SessionService.utc_now(),
                revoke_reason=reason,
                is_active=False,
            )
        )

        await db.flush()

        return result.rowcount or 0

    # ============================================================
    # REVOKE ALL USER SESSIONS
    # ============================================================

    @staticmethod
    async def revoke_all_user_sessions(
        db: AsyncSession,
        user_id: UUID,
        reason: str = REASON_PASSWORD_RESET,
    ) -> int:
        """
        Revoke every active session belonging to a user.

        Returns the number of sessions affected.
        """

        result = await db.execute(
            update(UserSession)
            .where(
                UserSession.user_id == user_id,
                UserSession.is_active.is_(True),
            )
            .values(
                revoked_at=SessionService.utc_now(),
                revoke_reason=reason,
                is_active=False,
            )
        )

        await db.flush()

        return result.rowcount or 0

    # ============================================================
    # DEVICE SESSION LOOKUP
    # ============================================================

    @staticmethod
    async def get_active_device_session(
        db: AsyncSession,
        user_id: UUID,
        device_id: str,
    ) -> Optional[UserSession]:
        """
        Find the active session for a particular device.
        """

        sessions = (
            await db.scalars(
                select(UserSession).where(
                    UserSession.user_id == user_id,
                    UserSession.device_id == device_id,
                    UserSession.is_active.is_(True),
                    UserSession.revoked_at.is_(None),
                )
            )
        ).all()

        for session in sessions:
            if SessionService.is_valid(session):
                return session

        return None