"""create authentication tables

Revision ID: 55fd1c0613a9
Revises: 
Create Date: 2026-09-15 03:39:31.122200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55fd1c0613a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('account_status', sa.Enum('active', 'pending', 'suspended', 'disabled', 'deleted', name='account_status'), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_subject', sa.String(length=255), nullable=True),
    sa.Column('apple_subject', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('apple_subject', name=op.f('uq_users_apple_subject')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_subject', name=op.f('uq_users_google_subject')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index('ix_users_account_status', 'users', ['account_status'], unique=False)
    op.create_table('email_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verifications'))
    )
    op.create_index('ix_email_verifications_email', 'email_verifications', ['email'], unique=False)
    op.create_index('ix_email_verifications_expires_at', 'email_verifications', ['expires_at'], unique=False)
    op.create_index('ix_email_verifications_token_hash', 'email_verifications', ['token_hash'], unique=False)
    op.create_index('ix_email_verifications_user_id', 'email_verifications', ['user_id'], unique=False)
    op.create_table('otp_records',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Enum('phone_signup', 'phone_login', 'phone_verification', 'email_signup', 'email_login', 'email_verification', 'password_reset', name='otp_purpose'), nullable=False),
    sa.Column('destination_type', sa.Enum('phone', 'email', name='otp_destination_type'), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_records'))
    )
    op.create_index('ix_otp_destination', 'otp_records', ['destination'], unique=False)
    op.create_index('ix_otp_expires_at', 'otp_records', ['expires_at'], unique=False)
    op.create_index('ix_otp_purpose_destination', 'otp_records', ['purpose', 'destination'], unique=False)
    op.create_index('ix_otp_user_id', 'otp_records', ['user_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets'))
    )
    op.create_index('ix_password_resets_email', 'password_resets', ['email'], unique=False)
    op.create_index('ix_password_resets_expires_at', 'password_resets', ['expires_at'], unique=False)
    op.create_index('ix_password_resets_token_hash', 'password_resets', ['token_hash'], unique=False)
    op.create_index('ix_password_resets_user_id', 'password_resets', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_device_id', 'sessions', ['device_id'], unique=False)
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_refresh_token_hash', 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index('ix_sessions_revoked_at', 'sessions', ['revoked_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_revoked_at', table_name='sessions')
    op.drop_index('ix_sessions_refresh_token_hash', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_index('ix_sessions_device_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_password_resets_user_id', table_name='password_resets')
    op.drop_index('ix_password_resets_token_hash', table_name='password_resets')
    op.drop_index('ix_password_resets_expires_at', table_name='password_resets')
    op.drop_index('ix_password_resets_email', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_otp_user_id', table_name='otp_records')
    op.drop_index('ix_otp_purpose_destination', table_name='otp_records')
    op.drop_index('ix_otp_expires_at', table_name='otp_records')
    op.drop_index('ix_otp_destination', table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_index('ix_email_verifications_user_id', table_name='email_verifications')
    op.drop_index('ix_email_verifications_token_hash', table_name='email_verifications')
    op.drop_index('ix_email_verifications_expires_at', table_name='email_verifications')
    op.drop_index('ix_email_verifications_email', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('ix_users_account_status', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
